CREATE TABLE IF NOT EXISTS SAMPLE (	
	SAMPLE_ID BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	SAMPLE_NAME VARCHAR(100) NOT NULL,
);

--INSERT INTO SAMPLE (SAMPLE_ID, SAMPLE_NAME) VALUES (1, 'SAMPLE NAME 1');
--INSERT INTO SAMPLE (SAMPLE_ID, SAMPLE_NAME) VALUES (2, 'SAMPLE NAME 2');
--INSERT INTO SAMPLE (SAMPLE_ID, SAMPLE_NAME) VALUES (3, 'SAMPLE NAME 3');
--INSERT INTO SAMPLE (SAMPLE_ID, SAMPLE_NAME) VALUES (4, 'SAMPLE NAME 4');
--INSERT INTO SAMPLE (SAMPLE_ID, SAMPLE_NAME) VALUES (5, 'SAMPLE NAME 5');